---
builds:
  - main
  - slim

options:
  common: "-Duseshrplib -Dvendorprefix=/usr/local"
  threaded: "-Dusethreads"

releases:
  - version: 5.43.8
    sha256:  44bc66a00ca494b66ed3f5221ad8b89271d8dca397a1fd0f5f6d0f047db0a2ca
    extra_flags: "-Dusedevel -Dversiononly=undef"
    debian_release:
      - bullseye
      - bookworm
      - trixie

  - version: 5.38.5
    sha256:  b7667d3ff309068852af7853910aaccec26c839d717402121b664ac705e07bfe
    debian_release:
      - bullseye
      - bookworm
      - trixie

  - version: 5.40.3
    sha256:  4c155b4e6160682b38919b55ac319081b898db11857cf18a7d9ffed2648ccaff
    debian_release:
      - bullseye
      - bookworm
      - trixie

  - version: 5.42.1
    sha256: 6f84e6dc8cce97181d1c6aeeb552c13775c91ded3c6c73743c9211af87b16bf8
    debian_release:
      - bullseye
      - bookworm
      - trixie
