---
builds:
  - main
  - slim

options:
  common: "-Duseshrplib -Dvendorprefix=/usr/local"
  threaded: "-Dusethreads"

releases:
  - version: 5.45.1
    sha256:  2b6d691916596835c411ee0181b6c66e4ee1c8d6ab60f8b0733c7c9cf8b58e3e
    extra_flags: "-Dusedevel -Dversiononly=undef"
    debian_release:
      - bullseye
      - bookworm
      - trixie

  - version: 5.40.4
    sha256:  3258564b644dc912f7367c4f49d6df77a855cdef9305c50801e03d09d39381af
    debian_release:
      - bullseye
      - bookworm
      - trixie

  - version: 5.42.2
    sha256: 9384e8deb75b7b1695e5637971b752281aaecd025a3d5d4734d33c1d0adfee47
    debian_release:
      - bullseye
      - bookworm
      - trixie

  - version: 5.44.0
    sha256: 3b855066b92491cb40e86affb1ca57d1a388aa43e51b91c7806a32c2f65f96c3
    debian_release:
      - bullseye
      - bookworm
      - trixie
