FROM alpine:{{alpine_tag_short}}

# This image deliberately retains the build toolchain at runtime (parallel
# to debian-main's buildpack-deps-based image), so cpanm/cpm installs of
# XS modules Just Work. This diverges from python:3-alpine / ruby:3-alpine
# which strip everything via scanelf-based runDeps pruning. Two virtual
# package sets: a permanent keeper, and a transient `.build-deps` purged
# at the end.

{{docker_copy_perl_patch}}
WORKDIR /usr/src/perl

RUN set -eux \
    && apk add --no-cache \
        build-base \
        bzip2-dev \
        ca-certificates \
        curl \
        libc-dev \
        linux-headers \
        make \
        openssl \
        openssl-dev \
        pkgconf \
        tzdata \
        wget \
        zlib-dev \
    && apk add --no-cache --virtual .build-deps \
        dpkg \
        dpkg-dev \
        gnupg \
        patch \
        pax-utils \
        procps \
        tar \
        xz \
    && curl -fL {{url}} -o perl-{{version}}.tar.gz \
    && echo '{{sha256}} *perl-{{version}}.tar.gz' | sha256sum -c - \
    && tar --strip-components=1 -xaf perl-{{version}}.tar.gz -C /usr/src/perl \
    && rm perl-{{version}}.tar.gz \
    && cat *.patch | patch -p1 \
    && gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)" \
    && archBits="$(dpkg-architecture --query DEB_BUILD_ARCH_BITS)" \
    && archFlag="$([ "$archBits" = '64' ] && echo '-Duse64bitall' || echo '-Duse64bitint')" \
    && ./Configure -Darchname="$gnuArch" "$archFlag" {{args}} {{extra_flags}} -des \
    && make -j$(nproc) \
    && {{test_alpine}} \
    && make install \
    && cd /usr/src \
    && curl -fLO {{cpanm_dist_url}} \
    && echo '{{cpanm_dist_sha256}} *{{cpanm_dist_name}}.tar.gz' | sha256sum -c - \
    && tar -xzf {{cpanm_dist_name}}.tar.gz && cd {{cpanm_dist_name}} \
    && {{cpanm_dist_patch_https}} \
    && {{cpanm_dist_patch_nolwp}} \
    && perl bin/cpanm . && cd /root \
    && curl -fLO '{{netssleay_dist_url}}' \
    && echo '{{netssleay_dist_sha256}} *{{netssleay_dist_name}}.tar.gz' | sha256sum -c - \
    && cpanm --notest --from $PWD {{netssleay_dist_name}}.tar.gz \
    && curl -fLO '{{iosocketssl_dist_url}}' \
    && echo '{{iosocketssl_dist_sha256}} *{{iosocketssl_dist_name}}.tar.gz' | sha256sum -c - \
    && SSL_CERT_DIR=/etc/ssl/certs cpanm --notest --from $PWD {{iosocketssl_dist_name}}.tar.gz \
    && curl -fL {{cpm_dist_url}} -o /usr/local/bin/cpm \
    # sha256 checksum is from docker-perl team, cf https://github.com/docker-library/official-images/pull/12612#issuecomment-1158288299
    && echo '{{cpm_dist_sha256}} */usr/local/bin/cpm' | sha256sum -c - \
    && chmod +x /usr/local/bin/cpm \
    && apk del --no-network .build-deps \
    && rm -fr /root/.cpanm /root/{{netssleay_dist_name}}* /root/{{iosocketssl_dist_name}}* /usr/src/perl /usr/src/{{cpanm_dist_name}}* /tmp/* \
    && cpanm --version && cpm --version

WORKDIR /usr/src/app

CMD ["perl{{version}}","-de0"]
